routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('timeline');
})->name('home');

Route::middleware('auth')->group(function() {
    Route::get('timeline', 'TimelineController')->name('timeline');
    Route::livewire('status/{hash}/edit', 'status.edit')->layout('layouts.app')->name('status.edit');
    Route::livewire('status/{hash}/delete', 'status.delete')->layout('layouts.modal')->name('status.delete');
});

Route::livewire('settings', 'account.edit')->layout('layouts.app', ['title' => 'Settings'])->name('settings')->middleware('auth');
Route::livewire('user/{identifier}', 'account.show')->layout('layouts.app')->name('account.show');
Route::get("user/{identifier}/{follow}", "FollowingController")->name('account.following');

Route::livewire('status/{hash}', 'status.show')->layout('layouts.app')->name('status.show');

Route::middleware('guest')->group(function () {
    Route::view('login', 'auth.login')->name('login');
    Route::view('register', 'auth.register')->name('register');
});

Route::view('password/reset', 'auth.passwords.email')->name('password.request');
Route::get('password/reset/{token}', 'Auth\PasswordResetController')->name('password.reset');

Route::middleware('auth')->group(function () {
    Route::view('email/verify', 'auth.verify')->middleware('throttle:6,1')->name('verification.notice');
    Route::get('email/verify/{id}/{hash}', 'Auth\EmailVerificationController')->middleware('signed')->name('verification.verify');

    Route::post('logout', 'Auth\LogoutController')->name('logout');

    Route::view('password/confirm', 'auth.passwords.confirm')->name('password.confirm');
});

app/Models/Timeline/Status.php
<?php

namespace App\Models\Timeline;

use App\Models\User;
use App\Traits\Likeable;
use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    use Likeable;
    protected $fillable = ['hash', 'body'];
    protected $withCount = ['comments'];
    public function getPublishedAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Livewire/Account/Edit.php
<?php

namespace App\Http\Livewire\Account;
use Livewire\Component;
use Livewire\WithFileUploads;

class Edit extends Component
{
    use WithFileUploads;
    public $name;
    public $username;
    public $picture;
    public $description;
    public function mount()
    {
        $this->name = auth()->user()->name;
        $this->username = auth()->user()->username;
        $this->description = auth()->user()->description;
    }

    public function updated($field)
    {
        $this->validateOnly($field, [
            'username' => 'min:3|max:25|unique:users,username,' . auth()->id(),
            'name' => 'min:3|string',
        ]);
    }

    public function update()
    {
        $this->validate([
            'picture' => $this->picture ? 'image|mimes:jpg,jpeg,png' : '',
            'username' => 'required|min:3|max:25|unique:users,username,' . auth()->id(),
            'name' => 'required|min:3|string',
        ]);

        if ($this->picture) {
            \Storage::delete(auth()->user()->picture);
            $picture = $this->picture->store('images/profile');
        } else {
            $picture = auth()->user()->picture ?? null;
        }
        auth()->user()->update([
            'name' => $this->name,
            'description' => $this->description,
            'username' => $this->username,
            'picture' => $picture,
        ]);

        $identifier = auth()->user()->usernameOrHash;
        return redirect()->to("user/{$identifier}");
    }

    public function render()
    {
        return view('livewire.account.edit');
    }
}

app/Http/Livewire/Account/Show.php
<?php

namespace App\Http\Livewire\Account;

use App\Models\User;
use Livewire\Component;
use App\Models\Timeline\Status;

class Show extends Component
{
    public $user;
    public $perPage = 10;
    public $bio;
    public $readmore = true;
    public function loadMore()
    {
        // sleep(1);
        $this->perPage += 10;
    }

    public function mount($identifier)
    {
        $this->user = User::where('username', $identifier)->orWhere('hash', $identifier)->first();
        $this->bio = \Str::limit($this->user->description, 120);
    }

    public function readMore()
    {
        $this->bio = $this->user->description;
        $this->readmore = false;
    }

    public function less()
    {
        $this->bio = \Str::limit($this->user->description, 120);
        $this->readmore = true;
    }

    public function render()
    {
        $statuses = $this->user->statuses()->with('user')->latest()->paginate($this->perPage);
        return view('livewire.account.show', compact('statuses'));
    }
}

app/Http/Livewire/Comment/Create.php
<?php

namespace App\Http\Livewire\Comment;

use Carbon\Carbon;
use Livewire\Component;

class Create extends Component
{
    public $body = "";
    public $status;
    public function mount($status)
    {
        $this->status = $status;
    }

    public function store()
    {
        $this->validate([
            'body' => 'required',
        ]);

        $commentId = auth()->user()->comments()->create([
            'status_id' => $this->status->id,
            'body' => $this->body,
            'hash' => \Str::random(22) . strtotime(Carbon::now()),
        ]);

        $this->body = "";

        $this->emit('commentAdded', $commentId->id);
    }

    public function render()
    {
        return view('livewire.comment.create');
    }
}

app/Http/Livewire/Comment/Index.php
<?php

namespace App\Http\Livewire\Comment;

use Carbon\Carbon;
use Livewire\Component;
use App\Models\Timeline\Comment;

class Index extends Component
{
    public $body = "";
    public $status;
    public $commendId;
    public $commentParentId;
    protected $listeners = ['commentAdded'];
    public function commentAdded($commendId) {}

    public function mount($status)
    {
        $this->status = $status;
    }

    public function showReplyForm($id)
    {
        $this->commentParentId = $id;
        $username = Comment::find($this->commentParentId)->user->usernameOrHash;
        $this->body = "@{$username} ";
    }

    public function reply()
    {
        $this->validate([
            'body' => 'required|max:255',
        ]);

        auth()->user()->comments()->create([
            'parent_id' => $this->commentParentId ?? null,
            'status_id' => $this->status->id,
            'body' => $this->body,
            'hash' => \Str::random(22) . strtotime(Carbon::now()),
        ]);

        $this->body = "";
    }

    public function render()
    {
        $comments = $this->status->comments()->where('parent_id', null)->withCount('children')->get();
        return view('livewire.comment.index', compact('comments'));
    }
}

app/Http/Livewire/Comment/Like.php
<?php

namespace App\Http\Livewire\Comment;

use Livewire\Component;

class Like extends Component
{
    public $comment;
    public function mount($comment)
    {
        $this->comment = $comment;
    }

    public function like()
    {
        if ($this->comment->isLiked()) {
            auth()->user()->likes()->delete($this->comment->likes);
        } else {
            auth()->user()->likes()->save($this->comment->likes()->make());
        }
    }

    public function render()
    {
        return view('livewire.comment.like');
    }
}

app/Http/Livewire/Follow/Button.php
<?php

namespace App\Http\Livewire\Follow;

use Livewire\Component;

class Button extends Component
{
    public $user;
    public function mount($user)
    {
        $this->user = $user;
    }

    public function follow()
    {
        auth()->user()->follow($this->user);
        $this->emit('statisticUpdated');
    }

    public function unfollow()
    {
        auth()->user()->unfollow($this->user);
        $this->emit('statisticUpdated');
    }

    public function render()
    {
        return view('livewire.follow.button');
    }
}

app/Http/Livewire/Follow/Statistic.php
<?php

namespace App\Http\Livewire\Follow;

use Livewire\Component;

class Statistic extends Component
{
    public $user;
    protected $listeners = ['statisticUpdated'];

    public function statisticUpdated() {}

    public function mount($user)
    {
        $this->user = $user;
    }

    public function render()
    {
        return view('livewire.follow.statistic');
    }
}

app/Http/Livewire/Navbar.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Navbar extends Component
{
    public function render()
    {
        return view('livewire.navbar');
    }
}

app/Http/Livewire/Status/Block.php
<?php

namespace App\Http\Livewire\Status;

use Livewire\Component;

class Block extends Component
{
    public $status;
    public function mount($status)
    {
        $this->status = $status;
    }

    public function render()
    {
        return view('livewire.status.block');
    }
}

app/Http/Livewire/Status/Create.php
<?php

namespace App\Http\Livewire\Status;

use Carbon\Carbon;
use Livewire\Component;

class Create extends Component
{
    public $body = "";
    public function updated($fields)
    {
        $this->validateOnly($fields, [
            'body' => 'string|max:355',
        ]);
    }

    public function store()
    {
        $this->validate([
            'body' => 'required',
        ]);

        $status = auth()->user()->statuses()->create([
            'hash' => \Str::random(22) . strtotime(Carbon::now()),
            'body' => $this->body,
        ]);

        $this->body = "";

        $this->emit("statusUpdated", $status->id);
    }

    public function render()
    {
        return view('livewire.status.create');
    }
}

app/Http/Livewire/Status/Delete.php
<?php

namespace App\Http\Livewire\Status;

use App\Models\Timeline\Status;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Livewire\Component;

class Delete extends Component
{
    use AuthorizesRequests;
    public $status;
    public function mount($hash)
    {
        $this->status = Status::where('hash', $hash)->firstOrFail();
    }

    public function destroy()
    {
        $this->authorize('update', $this->status);
        $this->status->delete();
        return redirect()->route('account.show', $this->status->user->usernameOrHash);
    }


    public function render()
    {
        $this->authorize('update', $this->status);
        return view('livewire.status.delete');
    }
}

app/Http/Livewire/Status/Edit.php
<?php

namespace App\Http\Livewire\Status;

use Livewire\Component;
use App\Models\Timeline\Status;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Edit extends Component
{
    use AuthorizesRequests;
    public $status;
    public $body;
    public function mount($hash)
    {
        $this->status = Status::where('hash', $hash)->firstOrFail();
        $this->body = $this->status->body;
    }

    public function update()
    {
        $this->authorize('update', $this->status);
        $this->status->update([
            'body' => $this->body,
        ]);

        return redirect()->route('status.show', $this->status->hash);
    }

    public function render()
    {
        $this->authorize('update', $this->status);
        return view('livewire.status.edit');
    }
}

app/Http/Livewire/Status/Index.php
<?php

namespace App\Http\Livewire\Status;

use App\Models\Timeline\Status;
use Livewire\Component;

class Index extends Component
{
    public $statusId;
    public $perPage = 10;
    protected $listeners = [
        "statusUpdated",
    ];

    public function statusUpdated($statusId) {}

    public function loadMore()
    {
        // sleep(1);
        $this->perPage += 10;
    }

    public function render()
    {
        $ids = auth()->user()->follows()->pluck('id');
        $ids->push(auth()->id());
        $statuses = Status::whereIn('user_id', $ids)->with('user')->latest()->paginate($this->perPage);
        return view('livewire.status.index', compact('statuses'));
    }
}

app/Http/Livewire/Status/Like.php
<?php

namespace App\Http\Livewire\Status;

use Livewire\Component;

class Like extends Component
{
    public $status;
    public function mount($status)
    {
        $this->status = $status;
    }

    public function like()
    {
        if ($this->status->isLiked()) {
            auth()->user()->likes()->delete($this->status->likes);
        } else {
            auth()->user()->likes()->save($this->status->likes()->make());
        }
    }

    public function render()
    {
        return view('livewire.status.like');
    }
}

app/Http/Livewire/Status/Show.php
<?php

namespace App\Http\Livewire\Status;

use App\Models\Timeline\Status;
use Livewire\Component;

class Show extends Component
{
    public $status = [];
    public function mount($hash)
    {
        $this->status = Status::with('user')->where('hash', $hash)->firstOrFail();
    }

    public function render()
    {
        return view('livewire.status.show');
    }
}

resources/views/livewire/status/block.blade.php
<div class="flex w-full" wire:poll.750ms>
    <div class="flex-shrink-0 mr-3">
        <a href="{{ route('account.show', ['identifier' => $status->user->usernameOrHash]) }}">
            <img class="w-16 h-16 rounded-full object-cover object-center" src="{{ $status->user->gravatar() }}">
        </a>
    </div>
    <div class="w-full relative">
        <div class="flex justify-between" x-data="{ dropdownIsOpen: false }">
            <a href="{{ route('account.show', ['identifier' => $status->user->usernameOrHash]) }}" class="font-semibold text-cool-gray-900 hover:underline">{{ $status->user->name }}</a>
            @can('update', $status)
                <button @click="dropdownIsOpen = !dropdownIsOpen" class="hover:bg-cool-gray-100 p-1 rounded-full focus:outline-none">
                    <svg class="w-5 h-5" viewBox="0 0 16 16" class="bi bi-chevron-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                    </svg>
                </button>
                <div :class="{ 'hidden': !dropdownIsOpen }" class="text-sm bg-white border border-cool-gray-200 rounded py-2 w-48 absolute right-0 top-0 mt-8">
                    <a href="{{ route('status.edit', $status->hash) }}" class="block px-3 py-1 hover:bg-cool-gray-100 text-cool-gray-600 hover:text-cool-gray-800">Edit the status</a>
                    <a href="{{ route('status.delete', $status->hash) }}" class="block px-3 py-1 hover:bg-cool-gray-100 text-cool-gray-600 hover:text-cool-gray-800">Remove the status</a>
                </div>
            @endcan
        </div>
        <a href="{{ route('status.show', $status->hash) }}">
            <div class="text-sm text-cool-gray-400 mb-3">{{ $status->published }}</div>
            <div class="text-cool-gray-700 leading-relaxed">{!! nl2br($status->body) !!}</div>
            <div class="text-sm text-cool-gray-400 mt-4 flex items-center -mx-4">
                <div class="flex items-center mx-4">
                    <svg class="w-5 h-5 mr-3" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                        <path d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"></path>
                    </svg>
                    <a href="#showReplyForm">
                        {{ $status->comments_count }} {{ Str::plural('Comment', $status->comments_count) }}
                    </a>
                </div>
                <livewire:status.like :key="$status->id" :status="$status"/>
            </div>
        </a>
    </div>
</div>

resources/views/livewire/status/create.blade.php
<div class="border border-cool-gray-200 mb-10 rounded-lg overflow-hidden">
    <div class="px-4 py-3 bg-cool-gray-100 border-b border-cool-gray-200 text-cool-gray-700 font-semibold">
        Your Status
    </div>
    <form wire:submit.prevent="store">
        <div class="p-4 bg-cool-gray-50">
            <textarea placeholder="What's in your mind ?" wire:model="body" class="form-textarea w-full resize-none border-0 focus:shadow-none p-0"></textarea>
            @error('body')
                <div class="text-red-500 text-sm mt-2">{{ $message }}</div>
            @enderror
        </div>

        <div class="flex justify-end px-4 py-2 bg-cool-gray-100 border-t border-cool-gray-200">
            <x-button.secondary>Post</x-button.secondary>
        </div>
    </form>
</div>

resources/views/livewire/status/delete.blade.php
<div class="container">
    <div class="bg-white px-10 py-5 rounded-lg border border-cool-gray-200 w-full lg:w-1/2 lg:mx-auto text-center">
        <div class="text-cool-gray-700">
            <div class="text-xl font-bold mb-5">
                Are you sure ?
            </div>
            <div class="flex items-start border border-cool-gray-200 rounded-lg p-4 mb-5 bg-cool-gray-50">
                <img class="mr-3 w-16 h-16 rounded-full object-cover object-center" src="{{ $status->user->gravatar() }}">
                <div class="text-left">
                    <div class="text-sm text-cool-gray-400 mb-3">{{ $status->published }}</div>
                    <div class="text-cool-gray-700 leading-relaxed">{!! nl2br($status->body) !!}</div>
                    <div class="text-sm text-cool-gray-400 mt-4 flex items-center -mx-4">
                        <div class="flex items-center mx-4">
                            <svg class="w-5 h-5 mr-3" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                                <path d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"></path>
                            </svg>
                            23 Comments
                        </div>
                        <div class="flex items-center mx-4">
                            <svg class="w-5 h-5 mr-3" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
                                <path d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5"></path>
                            </svg>
                            120 Likes
                        </div>
                    </div>
                </div>
            </div>

            <button wire:click.prevent="destroy" class="border border-red-500 bg-red-500 hover:bg-red-600 px-4 py-2 rounded-lg text-center inline-block text-white">Delete</button>
            <a class="border border-cool-gray-200 bg-white hover:bg-cool-gray-100 px-4 py-2 rounded-lg text-center inline-block" href="{{ route('status.show', $status->hash) }}">Cancel</a>
        </div>
    </div>
</div>

resources/views/livewire/status/edit.blade.php
<div class="p-4">
    <div class="w-full">
        <div class="border border-cool-gray-200 mb-10 rounded-lg overflow-hidden">
            <div class="px-4 py-3 bg-cool-gray-100 border-b border-cool-gray-200 text-cool-gray-700 font-semibold">
                Your Status
            </div>
            <form wire:submit.prevent="update">
                <div class="p-4 bg-cool-gray-50">
                    <textarea placeholder="What's in your mind ?" wire:model="body" class="form-textarea w-full resize-none border-0 focus:shadow-none p-0">{{ old('body') ?? $status->body }}</textarea>
                    @error('body')
                    <div class="text-red-500 text-sm mt-2">{{ $message }}</div>
                    @enderror
                </div>

                <div class="flex justify-end px-4 py-2 bg-cool-gray-100 border-t border-cool-gray-200">
                    <x-button.secondary>Update</x-button.secondary>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/livewire/status/index.blade.php
<div>
    @foreach($statuses as $status)
        <div class="mb-10">
            <livewire:status.block :status="$status" :key="$status->id" />
        </div>
    @endforeach

    @if($statuses->hasMorePages())
        <div class="flex justify-center">
            <x-button.primary wire:click.prevent="loadMore">
                <span wire:loading>
                    Please wait . . .
                </span>
                <span wire:loading.class="hidden">
                    Load More
                </span>
            </x-button.primary>
        </div>
    @endif
</div>

resources/views/livewire/status/like.blade.php
<div class="flex items-center mx-4">
    <svg class="w-5 h-5 mr-3 {{ $status->isLiked() ? 'text-blue-500' : '' }}" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
        <path d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5"></path>
    </svg>

    {{ $status->likes()->count() }} &nbsp;

    <button class="focus:outline-none" wire:click="like">
        {{ Str::plural('like', $status->likes()->count()) }}
    </button>
</div>

resources/views/livewire/status/show.blade.php
<div class="p-4">
    <div class="border border-cool-gray-300 rounded-lg p-5 mb-5">
        <livewire:status.block :status="$status" :key="$status->id" />
    </div>

    <livewire:comment.index :status="$status" :key="$status->id" />
    @if(Auth::check() && !$status->comments_count)
        <livewire:comment.create :status="$status" :key="$status->id" />
    @endif
</div>